import { render, screen } from "@testing-library/react";
import RootLayout, { metadata } from "../layout";

// Mock next/font/google
jest.mock("next/font/google", () => ({
  Geist: () => ({
    variable: "--font-geist-sans",
  }),
  Geist_Mono: () => ({
    variable: "--font-geist-mono",
  }),
}));

// Suppress expected DOM nesting warnings from rendering <html> in jsdom
const originalConsoleError = console.error;
beforeAll(() => {
  console.error = (...args: unknown[]) => {
    const msg = typeof args[0] === "string" ? args[0] : "";
    if (msg.includes("cannot be a child of")) return;
    originalConsoleError(...args);
  };
});
afterAll(() => {
  console.error = originalConsoleError;
});

describe("RootLayout", () => {
  it("renders children", () => {
    render(
      <RootLayout>
        <div data-testid="child">Test Child</div>
      </RootLayout>,
      { container: document.documentElement }
    );
    expect(screen.getByTestId("child")).toBeInTheDocument();
    expect(screen.getByText("Test Child")).toBeInTheDocument();
  });

  it("applies font variables to body", () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>,
      { container: document.documentElement }
    );
    const body = document.querySelector("body");
    expect(body?.className).toContain("--font-geist-sans");
    expect(body?.className).toContain("--font-geist-mono");
  });
});

describe("metadata", () => {
  it("has the correct title", () => {
    expect(metadata.title).toBe("Create Next App");
  });

  it("has the correct description", () => {
    expect(metadata.description).toBe("Generated by create next app");
  });
});
